// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModelSQLLiteFarm
{
    [Table("Schedule")]
    public partial class Schedule
    {
        [Key]
        public int JobScheduleID { get; set; }

        [Required]
        public int PrinterID { get; set; }

        public int JobID { get; set; }

        [Column(TypeName = "DateTime")]
        public DateTime? TimeStart { get; set; }

        [Column(TypeName = "DateTime")]
        public DateTime? TimeEnd { get; set; }

        public double? MR_Time { get; set; }
        public double? RO_Time { get; set; }
        
        public int? ScheduleWeek { get; set ; }

        [ForeignKey(nameof(JobID))]
        public virtual PrintJob PrintJob { get; set; }

        [ForeignKey(nameof(PrinterID))]
        public virtual Printer Printer { get; set; }
    }
}