// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    public partial class Material
    {
        [Key]
        public int MaterialID { get; set; }
        [StringLength(10)]
        public string MaterialName { get; set; }
        public double? MaterialPrice { get; set; }
    }
}