// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    public partial class Order
    {
        public Order()
        {
            PrintJobs = new HashSet<PrintJob>();
        }

        [Key]
        public int OrderID { get; set; }

        [Required]
        [StringLength(50)]
        public string CustomerName { get; set; }

        [Required]
        [StringLength(50)]
        public string OrderName { get; set; }
        public double OrderPrice { get; set; }
        
        [Column(TypeName = "DateTime")]
        public DateTime? DateIn { get; set; }
        
        [Column(TypeName = "DateTime")]
        public DateTime? DateDue { get; set; }
        public virtual ICollection<PrintJob> PrintJobs { get; set; }
    }
}