// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    [Keyless]
    public partial class PrintersMaterial
    {
        public int? PMPrintersFK { get; set; }
        public int? PMMaterialsFK { get; set; }

        [ForeignKey(nameof(PMMaterialsFK))]
        public virtual Material PMMaterialsFKNavigation { get; set; }

        [ForeignKey(nameof(PMPrintersFK))]
        public virtual Printer PMPrintersFKNavigation { get; set; }
    }
}