// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    [Keyless]
    public partial class PrintersService
    {
        public int PSPrintersFK { get; set; }
        public int PSServicesFK { get; set; }

        [ForeignKey(nameof(PSPrintersFK))]
        public virtual Printer PSPrintersFKNavigation { get; set; }
        [ForeignKey(nameof(PSServicesFK))]
        public virtual ServiceLogEvent PSServicesFKNavigation { get; set; }
    }
}