// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    public partial class Printer
    {
        public Printer()
        {
            Schedules = new HashSet<Schedule>();
        }

        [Key]
        public int PrinterID { get; set; }
        [Required]
        [StringLength(10)]
        public string PrinterType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PrinterPurchDate { get; set; }
        public double PrinterPurchPrice { get; set; }
        public double? ServiceTimeEst { get; set; }

        [InverseProperty(nameof(Schedule.Printer))]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}