// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    public partial class PrintJob
    {
        public PrintJob()
        {
            Schedules = new HashSet<Schedule>();
        }

        [Key]
        public int JobID { get; set; }
        [Required]
        [StringLength(30)]
        public string JobName { get; set; }
        [StringLength(30)]
        public string JobOrder { get; set; }
        [StringLength(3)]
        public string Material { get; set; }
        public double? WeightMaterial { get; set; }
        public int? NozzleDiam_mm { get; set; }
        public int? LayerHeight { get; set; }
        public int? VolX { get; set; }
        public int? VolY { get; set; }
        public int? VolZ { get; set; }

        [StringLength(30)]
        public string GcodeAdresse { get; set; }
        public int? OrderID { get; set; }
        public double? PrintTime { get; set; }

        [ForeignKey(nameof(OrderID))]
        [InverseProperty("PrintJobs")]
        public virtual Order Order { get; set; }
        [InverseProperty(nameof(Schedule.PrintJob))]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}