// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    public partial class PrintJob
    {
        public PrintJob()
        {
            //Schedules = new HashSet<Schedule>();
            Schedule PrintSchedule = new();
        }

        [Key]
        public int JobID { get; set; }
        [Required]

        [StringLength(50)]
        public string JobName { get; set; }
        public int? OrderID { get; set; }

        [ForeignKey(nameof(OrderID))]
        public virtual Order Order { get; set; }

        [StringLength(3)]
        public string Material { get; set; }
        public double? WeightMaterial { get; set; }
        public double? NozzleDiam_mm { get; set; }
        public int? LayerHeight { get; set; }
        public int? VolX { get; set; }
        public int? VolY { get; set; }
        public int? VolZ { get; set; }

        public int PrinterType { get; set; }

        [StringLength(200)]
        public string GcodeAdresse { get; set; }

        public double? PrintTime { get; set; }


        [ForeignKey(nameof(JobID))]

        public virtual Schedule PrintSchedule{ get; set; }
    }
}