// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    [Table("Schedule")]
    public partial class Schedule
    {
        [Key]
        public int JobScheduleID { get; set; }
        public int PrintJobID { get; set; }
        public int PrinterID { get; set; }

        [Column(TypeName = "DateTime")]
        public DateTime? TimeStart { get; set; }
        public double? MR_Time { get; set; }
        public double? RO_Time { get; set; }
        
        public int? ScheduleWeek { get; set; }

        [ForeignKey(nameof(PrintJobID))]
        [InverseProperty("Schedules")]
        public virtual PrintJob PrintJob { get; set; }
        [ForeignKey(nameof(PrinterID))]
        [InverseProperty("Schedules")]
        public virtual Printer Printer { get; set; }
    }
}