// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model3DFarm
{
    public partial class ServiceLogEvent
    {
        [Key]
        public int EventID { get; set; }
        [Required]
        [StringLength(50)]
        public string EventName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventDate { get; set; }
        public int? EventLength_hrs { get; set; }
        [StringLength(10)]
        public string EventCategory { get; set; }
        [StringLength(10)]
        public string EventCost_euro { get; set; }
    }
}